apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      imagePullSecrets:
      - name: gcr-access
      containers:
      - image: gcr.io/coit-microservices/mydb:v1
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: DEVOPS1
        - name: MYSQL_PASSWORD
          value: DEVOPS1
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: dbuser
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: db-creds
          mountPath: /root/.ssh
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: db-creds
        secret:
          secretName: wp-secrets
          items: 
            - key: mysql_pass 
              path: .my.pass
            - key: ssh_public_key
              path: authorized_keys

